### ISSUE TITLE
UI does not handle display scaling correctly

### ISSUE THREAD

**Issue by BenjaminUrquhart** [kwsch/ItemPrinterDeGacha#1]
I have my main display set to 125% scale which makes some UI elements start overlapping or otherwise hard to read.

I would fix this myself, but C# is not my strong suit and I'm not sure how to use WinForms either.

![ApplicationFrameHost_U2eZukocnW](https://github.com/kwsch/ItemPrinterDeGacha/assets/24701883/9d67bda1-4641-4255-8f56-fa4b1db41679)
![ApplicationFrameHost_b0cwpbyEBc](https://github.com/kwsch/ItemPrinterDeGacha/assets/24701883/b92ad4b3-5019-46e2-a5b6-ce2f5a91e406)

**Comment by kwsch** [comment]
Checking my other winforms projects, might need to have this added to the Main Form's designer:

```
            AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
```

**Comment by kwsch** [comment]
[ItemPrinterDeGacha (dpi).zip](https://github.com/kwsch/ItemPrinterDeGacha/files/14927647/ItemPrinterDeGacha.dpi.zip)
Rebuilt with above commit change; is there any difference compared to when it was `AutoScaleMode.Font`?

**Comment by kwsch** [comment]
[ItemPrinterDeGacha (dpi 2).zip](https://github.com/kwsch/ItemPrinterDeGacha/files/14927957/ItemPrinterDeGacha.dpi.2.zip)
More changes that probably makes it behave correct now...

**Comment by BenjaminUrquhart** [comment]
My antivirus is eating these downloads, but I'm still getting the problem when pulling from the "dpi" branch

**Comment by BenjaminUrquhart** [comment]
After messing with Defender, both executables you sent still have scaling problems

**Comment by bdawg1989** [comment]
> [ItemPrinterDeGacha (dpi 2).zip](https://github.com/kwsch/ItemPrinterDeGacha/files/14927957/ItemPrinterDeGacha.dpi.2.zip) More changes that probably makes it behave correct now...

I'm fixing it now, will do a PR soon.

![image](https://github.com/kwsch/ItemPrinterDeGacha/assets/80122551/4dd7a5c6-156d-422f-8feb-3b793a9c42c1)

How does that look?

![image](https://github.com/kwsch/ItemPrinterDeGacha/assets/80122551/e06cfd34-8f79-4d4a-8636-eaced18557b6)

**Comment by kwsch** [comment]
Works fine on the commit I'm about to push; I think I might have missed one or two things in my branch.
![image](https://github.com/kwsch/ItemPrinterDeGacha/assets/6393368/1070563a-95f3-4d7f-a4f5-faa14c39d792)

**Comment by BenjaminUrquhart** [comment]
can confirm this works, thank you!
